services:
  - type: web
    name: stocklumo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: Finnhub__ApiKey
        sync: false
